{{- if .Values.runnerServiceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.runnerServiceAccount.name }}
  namespace: {{ .Values.runnerScaleSet.namespace }}
  labels:
    {{- include "github-arc-runners.labels" . | nindent 4 }}
  {{- with .Values.runnerServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
