# This is a template for the GitHub App credentials secret
# You need to create this secret manually or use a secret management solution
# like Sealed Secrets, External Secrets Operator, or ArgoCD Vault Plugin

# Example using kubectl:
# kubectl create secret generic github-app-credentials \
#   --namespace=github-runners \
#   --from-literal=github_app_id=YOUR_APP_ID \
#   --from-literal=github_app_installation_id=YOUR_INSTALLATION_ID \
#   --from-file=private-key=path/to/your/private-key.pem

# Example YAML (DO NOT commit this with real values):
# apiVersion: v1
# kind: Secret
# metadata:
#   name: github-app-credentials
#   namespace: github-runners
# type: Opaque
# data:
#   github_app_id: BASE64_ENCODED_APP_ID
#   github_app_installation_id: BASE64_ENCODED_INSTALLATION_ID
#   private-key: BASE64_ENCODED_PRIVATE_KEY_PEM
