apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.runnerScaleSet.namespace }}
  labels:
    {{- include "github-arc-runners.labels" . | nindent 4 }}
    app.kubernetes.io/component: runners
